"""Model-level intelligence: sneaker-intel ML demand signal + live Reddit sentiment."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd

# Path to precomputed predictions JSON (generated by sneaker-intel ensemble)
_PREDICTIONS_PATH = (
    Path(__file__).parent.parent.parent.parent.parent
    / "data" / "processed" / "model_predictions.json"
)


@dataclass
class ModelIntelRow:
    """Combined ML demand signal + Reddit sentiment for one shoe model."""

    model: str
    brand: str
    retail_price: float
    demand_score: float      # 0.0–1.0 global percentile rank
    demand_multiplier: float # predicted_sale / retail (historical signal)
    demand_tier: str         # "High" | "Medium" | "Low"
    mention_count: int       # Reddit mentions
    avg_sentiment: float     # hybrid_score mean
    positive_pct: float
    negative_pct: float
    combined_score: float    # 0.0–1.0 composite


@dataclass
class ModelIntelligenceResult:
    """Output of ModelIntelligenceAnalyzer.analyze()."""

    rows: list[ModelIntelRow]
    summary_df: pd.DataFrame = field(default_factory=pd.DataFrame)
    predictions_meta: dict = field(default_factory=dict)


class ModelIntelligenceAnalyzer:
    """Join sneaker-intel ML demand predictions with live Reddit model-level sentiment."""

    DEMAND_WEIGHT = 0.55   # ML demand signal
    SENTIMENT_WEIGHT = 0.25
    MENTION_WEIGHT = 0.20

    def analyze(self, df: pd.DataFrame) -> ModelIntelligenceResult:
        """
        Args:
            df: Annotated Reddit DataFrame with 'models' and 'hybrid_score' columns.

        Returns:
            ModelIntelligenceResult with per-model rows and display-ready DataFrame.
        """
        predictions, meta = self._load_predictions()
        reddit_signals = self._aggregate_reddit(df)

        rows: list[ModelIntelRow] = []
        for pred in predictions:
            model = pred["model"]
            reddit = reddit_signals.get(model, {
                "mention_count": 0,
                "avg_sentiment": 0.0,
                "positive_pct": 0.0,
                "negative_pct": 0.0,
            })
            combined = self._combined_score(
                pred["demand_score"],
                reddit["avg_sentiment"],
                reddit["mention_count"],
                max_mentions=max((r["mention_count"] for r in reddit_signals.values()), default=1),
            )
            rows.append(ModelIntelRow(
                model=model,
                brand=pred["brand"],
                retail_price=pred["retail_price"],
                demand_score=pred["demand_score"],
                demand_multiplier=pred["demand_multiplier"],
                demand_tier=pred["demand_tier"],
                mention_count=reddit["mention_count"],
                avg_sentiment=reddit["avg_sentiment"],
                positive_pct=reddit["positive_pct"],
                negative_pct=reddit["negative_pct"],
                combined_score=round(combined, 4),
            ))

        rows.sort(key=lambda r: r.combined_score, reverse=True)
        summary_df = self._to_df(rows)
        return ModelIntelligenceResult(rows=rows, summary_df=summary_df, predictions_meta=meta)

    @staticmethod
    def _load_predictions() -> tuple[list[dict], dict]:
        if not _PREDICTIONS_PATH.exists():
            return [], {}
        with open(_PREDICTIONS_PATH) as f:
            data = json.load(f)
        meta = {k: v for k, v in data.items() if k != "models"}
        return data.get("models", []), meta

    @staticmethod
    def _aggregate_reddit(df: pd.DataFrame) -> dict[str, dict]:
        if "models" not in df.columns or "hybrid_score" not in df.columns:
            return {}

        df = df.copy()
        df["models"] = df["models"].apply(
            lambda x: list(x) if hasattr(x, "__iter__") and not isinstance(x, str) else []
        )
        exploded = df.explode("models")
        exploded = exploded[
            exploded["models"].notna()
            & (exploded["models"].astype(str).str.strip() != "")
            & (exploded["models"].astype(str) != "nan")
        ]

        if exploded.empty:
            return {}

        result = {}
        for model, grp in exploded.groupby("models"):
            scores = grp["hybrid_score"].dropna()
            n = len(scores)
            if n == 0:
                continue
            pos = (scores > 0.05).sum()
            neg = (scores < -0.05).sum()
            result[str(model)] = {
                "mention_count": n,
                "avg_sentiment": round(float(scores.mean()), 4),
                "positive_pct": round(pos / n * 100, 1),
                "negative_pct": round(neg / n * 100, 1),
            }
        return result

    def _combined_score(
        self,
        demand_score: float,
        avg_sentiment: float,
        mention_count: int,
        max_mentions: int,
    ) -> float:
        # Normalise sentiment from [-1, 1] to [0, 1]
        norm_sentiment = (avg_sentiment + 1) / 2
        # Normalise mentions to [0, 1]
        norm_mentions = mention_count / max(max_mentions, 1)
        return (
            self.DEMAND_WEIGHT * demand_score
            + self.SENTIMENT_WEIGHT * norm_sentiment
            + self.MENTION_WEIGHT * norm_mentions
        )

    @staticmethod
    def _to_df(rows: list[ModelIntelRow]) -> pd.DataFrame:
        return pd.DataFrame([
            {
                "Model": r.model,
                "Brand": r.brand,
                "Retail $": r.retail_price,
                "Demand Tier": r.demand_tier,
                "Demand Score": r.demand_score,
                "Demand Multiplier": r.demand_multiplier,
                "Reddit Mentions": r.mention_count,
                "Avg Sentiment": r.avg_sentiment,
                "Positive %": r.positive_pct,
                "Negative %": r.negative_pct,
                "Combined Score": r.combined_score,
            }
            for r in rows
        ])
